version: "3.7"
services:
 jupyter1:
  image: ml-dev-docker:1 
  restart: always
  container_name: jupyter1
  hostname: jupyter1
  privileged: true
  dns_search:
   - .steltix.com
  ports:
   - 80:80
   - 443:443
  environment:
   - TZ=Europe/Amsterdam
  volumes:
   - /docker/containers/jupyter1:/share
  sysctls:
  - net.ipv4.ip_unprivileged_port_start=0
  user: root
  deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 2
            capabilities: [gpu]
  networks:
    ipvlan1:
        ipv4_address: 192.168.1.181
  stop_grace_period: 5s
  labels:
   com.steltix.description: "Johan Jupyter and Cuda image"
   com.steltix.company: "Johan"
   com.steltix.component: "Jupyter Nvidia Cuda 12.2 "
   com.steltix.os: "Oracle Linux"
networks:
  ipvlan1:
    external: true

